name: publish website to cpanel
on: 
 push:
  branches:
   - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: born2hope/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{ secrets.ftp_password }}
